cos external observability fix
When attempting to enable cos observability after hitatchi storage is setup it cannot continue. gets error:
ValueError: storage-plan not found in tfhelpers
WARNING An unexpected error has occurred.

If cos is enabled prior to adding hitachi things work fine.

These changes to feature.py correct issues where storage-plan does not exist with storage-backend-plan which is the sunbeam storage plan used for that step

(cherry picked from commit 96bee5c7dd5131059281d2a7f83685f94a16a59e)
(cherry picked from commit 7f2535b1e2b4b4dc88ca0fd3b47762f3eb9486cb)
(cherry picked from commit 7070aca65af72c816784bd761e314066d4ffa00b)