fix: CI failures with terraform output
snap-openstack CI failed with following error [1]

+ sg snap_daemon 'openstack.sunbeam cluster bootstrap --manifest .github/assets/testing/edge.yml --accept-defaults --topology single --database single'
WARNING: Option --database is deprecated and the value is ignored. Instead user is prompted to select the database topology. The database topology can also be set via manifest.
Terraform output failed:
Error: Required plugins are not installed

snapcraft latest/stable moved to 9.x/stable which brings
charmcraft 2.35.0
commit: canonical/craft-parts#1424 [2] — cfdabafc1 "refactor: use pathlib internally"
changed the way `organize` deals with hidden files. The changed code
brings hidden files and in this case it brings .github, .gitignore
and .terraform.lock.hcl as part of the snap from build time
which triggered the error while DeployMicroovnStep tries to get
terraform output from openstack plan which is not initialized yet.
If the lock.hcl is not there, the terraform output returns {}.

Remove the hidden files from snapcraft.yaml for deploy-openstack part.

[1] https://github.com/canonical/snap-openstack/actions/runs/36387832192/job/108820008426?pr=929
[2] https://github.com/canonical/craft-parts/pull/1424

Assisted-by: z.ai/glm-5.3
Signed-off-by: Hemanth Nakkina <hemanth.nakkina@canonical.com>